name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code - on regarde la construction
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker login - Connection à docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build Docker image
        run: |
          docker build -t sergioamoncada/graphql:0.0.2 .

      - name: Push Docker image
        run: |
          docker push sergioamoncada/graphql:0.0.2

    # - name: Push the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
