name: Docker Image CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code - on regarde la construction
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker login - Connection à docker
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Commencement du login"
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
          echo "Fin du login"

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
